# Generated by Django 5.2.1 on 2025-05-17 11:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Communaute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(max_length=100, verbose_name="Nom de l'entreprise")),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('telephone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?[0-9 ]+$', 'Numéro de téléphone invalide')], verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('domaine', models.CharField(choices=[('PROG', 'Programmation'), ('MARK', 'Marketing'), ('COMPT', 'Comptabilité'), ('DESIGN', 'Design'), ('RH', 'Ressources Humaines'), ('AUTRE', 'Autre')], max_length=10, verbose_name="Domaine d'activité")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('site_web', models.URLField(blank=True, null=True, verbose_name='Site web')),
            ],
            options={
                'verbose_name': 'Membre de la communauté',
                'verbose_name_plural': 'Membres de la communauté',
                'ordering': ['nom_entreprise'],
                'indexes': [models.Index(fields=['nom_entreprise'], name='communautes_nom_ent_70a53a_idx'), models.Index(fields=['domaine'], name='communautes_domaine_c2b94f_idx')],
            },
        ),
    ]
