# Generated by Django 5.2.1 on 2025-05-17 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communautes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communaute',
            options={'ordering': ['nom_entreprise'], 'permissions': [('can_approve_communaute', 'Peut approuver les membres'), ('can_manage_communaute', 'Peut gérer tous les membres')], 'verbose_name': 'Membre de la communauté', 'verbose_name_plural': 'Membres de la communauté'},
        ),
        migrations.AddField(
            model_name='communaute',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communautes_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='communaute',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Visible publiquement'),
        ),
        migrations.AddField(
            model_name='communaute',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
        migrations.AddIndex(
            model_name='communaute',
            index=models.Index(fields=['is_public'], name='communautes_is_publ_097b8e_idx'),
        ),
    ]
